(function(){
"use strict";
const $=id=>document.getElementById(id); const num=v=>Number(v||0); const money=v=>num(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const today=()=>new Date().toISOString().slice(0,10);
function dateAdd(d,n){const x=new Date((d||today())+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function daysBetween(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function state(){try{return typeof window.ONDIS_STATE==='function'?window.ONDIS_STATE():{}}catch{return {}}}
function financeEntries(){return (state().FIN_ENTRIES||[]).filter(x=>!x.deleted)} function sales(){return (state().SALES||[]).filter(s=>s.status!=='cancelada')} function products(){return state().PRODUCTS||[]} function suppliers(){return (state().SUPPLIERS||[]).filter(s=>!s.deleted)} function notes(){return state().NOTES||[]}
function loadExtra(){try{return JSON.parse(localStorage.getItem('ondis_finance_v10')||'{}')}catch{return {}}} function saveExtra(o){localStorage.setItem('ondis_finance_v10',JSON.stringify(o))}
const defaultCenters=['Loja','Administrativo','Marketing','Equipe','Logística','Tecnologia']; const defaultBudgetCats=['Fornecedor','Aluguel','Folha / salários','Impostos','Marketing','Cartões','Serviços','Comissões','Pró-labore','Outros'];
function extra(){const e=loadExtra(); e.centers=e.centers?.length?e.centers:defaultCenters.slice(); e.budget=e.budget||{}; return e}
window.showFinance3Tab=function(tab){document.querySelectorAll('.fin3Nav button').forEach(b=>b.classList.toggle('active',b.dataset.fin3===tab));document.querySelectorAll('.fin3Pane').forEach(p=>p.classList.toggle('active',p.id==='fin3-'+tab));renderFinanceV10(tab)};
function bindFinNav(){document.querySelectorAll('.fin3Nav button').forEach(b=>b.addEventListener('click',()=>showFinance3Tab(b.dataset.fin3))); document.querySelectorAll('[data-cash-range]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-cash-range]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCash90(Number(b.dataset.cashRange||30))}));
 document.querySelectorAll('#nav [data-fin-open]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>showFinance3Tab(b.dataset.finOpen),40)));
 ['scRevenue','scCmv','scExpenses','scDiscount'].forEach(id=>$(id)?.addEventListener('input',renderScenario));
}
window.openFinanceComposer=function(type='payable'){if($('finType'))$('finType').value=type;if($('finComposerTitle'))$('finComposerTitle').textContent=type==='receivable'?'Nova conta a receber':'Nova conta a pagar';fillCostCenters();if($('finDue')&&!$('finDue').value)$('finDue').value=today(); if(window.openModal)window.openModal('financeComposer');else $('financeComposer')?.classList.add('open')};
window.focusFinanceEntry=function(){showFinance3Tab('pagar');openFinanceComposer('payable')};
window.addFinanceEntryV10=async function(){const desc=$('finDesc')?.value.trim(),amount=num($('finAmount')?.value);if(!desc)return alert('Informe a descrição.');if(amount<=0)return alert('Informe um valor maior que zero.'); const type=$('finType').value; if(typeof window.addFinanceEntry==='function'){const originalCat=$('finCategory').value; await window.addFinanceEntry(); const arr=financeEntries(); const newest=arr.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))[0]; if(newest){newest.costCenter=$('finCostCenter')?.value||'Loja';newest.notes=$('finNotes')?.value||'';} } else { const e=loadExtra();e.manual=e.manual||[];e.manual.push({id:'v10_'+Date.now(),description:desc,type,category:$('finCategory').value,costCenter:$('finCostCenter').value,amount,dueDate:$('finDue').value,status:$('finStatus').value,method:$('finMethod').value,notes:$('finNotes').value});saveExtra(e)} if(window.closeModal)window.closeModal('financeComposer');else $('financeComposer')?.classList.remove('open');renderFinanceV10(type==='receivable'?'receber':'pagar')};
function allEntries(){const e=extra();return financeEntries().concat(e.manual||[])}
function paidDate(x){return (x.paidAt||x.updatedAt||x.dueDate||'').slice(0,10)}
function monthSales(){const m=today().slice(0,7);return sales().filter(s=>(s.createdAt||'').slice(0,7)===m)}
function calcCore(){const ent=allEntries(),ms=monthSales(),rev=ms.reduce((a,s)=>a+num(s.total),0),cmv=ms.reduce((a,s)=>a+(s.items||[]).reduce((z,i)=>z+num(i.cost||i.custo||0)*num(i.qty||1),0),0);const payOpen=ent.filter(e=>e.type==='payable'&&e.status!=='paid').reduce((a,e)=>a+num(e.amount),0),recOpen=ent.filter(e=>e.type==='receivable'&&e.status!=='paid').reduce((a,e)=>a+num(e.amount),0),paidExp=ent.filter(e=>e.type==='payable'&&e.status==='paid'&&paidDate(e).slice(0,7)===today().slice(0,7)).reduce((a,e)=>a+num(e.amount),0),profit=rev-cmv-paidExp,margin=rev?profit/rev*100:0;return{rev,cmv,payOpen,recOpen,paidExp,profit,margin,ent,ms}}
function health(c){let score=72;if(c.profit<0)score-=25;if(c.margin<10)score-=15;else if(c.margin>20)score+=8;if(c.payOpen>c.recOpen+c.rev*.5)score-=15;if(c.recOpen>c.payOpen)score+=5;return Math.max(0,Math.min(100,Math.round(score)))}
function renderExecutive(){if(!$('fin3ExecutiveMetrics'))return;const c=calcCore(),h=health(c),overdue=c.ent.filter(e=>e.status!=='paid'&&e.dueDate&&e.dueDate<today()),overdueV=overdue.reduce((a,e)=>a+num(e.amount),0);$('fin3ExecutiveMetrics').innerHTML=[['Faturamento',money(c.rev)],['Lucro operacional',money(c.profit)],['Margem',c.margin.toFixed(1)+'%'],['Exposição vencida',money(overdueV)]].map(x=>`<div class="fin3Metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('fin3Health').textContent=h;$('fin3HealthBar').style.width=h+'%';$('fin3HealthText').textContent=h>=80?'Operação financeiramente saudável.':h>=60?'Saúde razoável, com pontos para acompanhar.':'A operação exige atenção financeira.'; const delta=c.recOpen-c.payOpen; $('fin3Headline').textContent=c.profit>=0?'Sua loja está gerando resultado — agora proteja o caixa.':'O resultado está pressionado — priorize margem e despesas.';$('fin3Narrative').textContent=`No mês: ${money(c.rev)} em vendas, ${money(c.profit)} de resultado estimado e ${money(Math.abs(delta))} de ${delta>=0?'folga entre recebíveis e contas':'pressão entre contas e recebíveis'}.`;
 const insights=[]; if(overdueV>0)insights.push(['!','Contas vencidas',`${money(overdueV)} exigem ação imediata.`]); if(c.margin<20)insights.push(['↗','Margem abaixo de 20%',`Margem atual estimada em ${c.margin.toFixed(1)}%.`]); if(c.payOpen>c.recOpen)insights.push(['↓','Pressão de caixa',`A pagar supera a receber em ${money(c.payOpen-c.recOpen)}.`]); if(!insights.length)insights.push(['✓','Financeiro sob controle','Nenhuma anomalia crítica detectada.']); $('fin3Insights').innerHTML=insights.map(i=>`<div class="fin3Insight"><i>${i[0]}</i><div><b>${i[1]}</b><small>${i[2]}</small></div></div>`).join(''); renderCapital(c);renderCash90(30,true)}
function renderCapital(c){if(!$('fin3Capital'))return;const fixedMonthly=Math.max(c.paidExp,c.rev*.12),reserve=Number(state().CFG?.otbReserve||10000),working=Math.max(0,c.recOpen-c.payOpen),days=fixedMonthly?Math.round((Math.max(0,working)+reserve)/(fixedMonthly/30)):0;const need=Math.max(fixedMonthly*.75,c.payOpen-c.recOpen,0);$('fin3Capital').innerHTML=[['Capital de giro estimado',money(working)],['Necessidade estimada',money(need)],['Reserva mínima',money(reserve)],['Cobertura operacional',days+' dias']].map(x=>`<div class="fin3CapitalCard"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function cashRows(days){const c=calcCore(),rows=[];let acc=Math.max(0,c.recOpen*.05);for(let i=0;i<days;i++){const d=dateAdd(today(),i),inflow=c.ent.filter(e=>e.type==='receivable'&&e.status!=='paid'&&e.dueDate===d).reduce((a,e)=>a+num(e.amount),0),outflow=c.ent.filter(e=>e.type==='payable'&&e.status!=='paid'&&e.dueDate===d).reduce((a,e)=>a+num(e.amount),0);const avgSales=c.rev/Math.max(1,new Date().getDate());const estimated=i<7?avgSales*.35:0;acc+=inflow+estimated-outflow;rows.push({d,inflow:inflow+estimated,outflow,net:inflow+estimated-outflow,acc})}return rows}
function cashSvg(rows){const vals=rows.map(r=>r.acc),min=Math.min(0,...vals),max=Math.max(1,...vals),w=900,h=220,pad=25,range=max-min||1,pts=rows.map((r,i)=>`${pad+i*(w-2*pad)/Math.max(1,rows.length-1)},${h-pad-(r.acc-min)/range*(h-2*pad)}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Saldo acumulado projetado"><defs><linearGradient id="cashFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--brand)" stop-opacity=".24"/><stop offset="1" stop-color="var(--brand)" stop-opacity="0"/></linearGradient></defs><line x1="25" y1="${h-pad-(0-min)/range*(h-2*pad)}" x2="875" y2="${h-pad-(0-min)/range*(h-2*pad)}" stroke="var(--line)" stroke-dasharray="4 5"/><polyline points="${pts}" fill="none" stroke="var(--brand)" stroke-width="3"/><polygon points="${pts} 875,195 25,195" fill="url(#cashFill)"/></svg>`}
function renderCash90(days=30,summary=false){const rows=cashRows(days);if($('fin3CashChart'))$('fin3CashChart').innerHTML=cashSvg(rows);const worst=[...rows].sort((a,b)=>a.acc-b.acc)[0],entries=rows.reduce((a,r)=>a+r.inflow,0),outs=rows.reduce((a,r)=>a+r.outflow,0);if($('fin3CashCards'))$('fin3CashCards').innerHTML=[['Entradas previstas',money(entries)],['Saídas previstas',money(outs)],['Saldo final',money(rows.at(-1)?.acc||0)],['Pior dia',worst?new Date(worst.d+'T12:00:00').toLocaleDateString('pt-BR'):'—']].map(x=>`<div class="fin3CapitalCard"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');if($('fin3CashTable'))$('fin3CashTable').innerHTML=rows.map(r=>`<tr><td>${new Date(r.d+'T12:00:00').toLocaleDateString('pt-BR')}</td><td class="financeRiskLow">${money(r.inflow)}</td><td>${money(r.outflow)}</td><td>${money(r.net)}</td><td><b>${money(r.acc)}</b></td><td><span class="status ${r.acc<0?'bad':r.acc<outs/days?'warn':'good'}">${r.acc<0?'Crítico':r.acc<outs/days?'Atenção':'Saudável'}</span></td></tr>`).join('');if($('fin3CashTimeline'))$('fin3CashTimeline').innerHTML=cashSvg(rows.slice(0,30));if($('cashInsight'))$('cashInsight').innerHTML=worst&&worst.acc<0?`⚠️ O ponto de maior pressão projetado ocorre em <b>${new Date(worst.d+'T12:00:00').toLocaleDateString('pt-BR')}</b>, com saldo estimado de <b>${money(worst.acc)}</b>.`:`✓ Nenhum saldo negativo foi projetado nos próximos ${days} dias.`}
function accountRows(type){const search=(type==='payable'?$('paySearch')?.value:$('recSearch')?.value||'').toLowerCase(),status=(type==='payable'?$('payStatus')?.value:$('recStatus')?.value||''),cc=$('payCostCenter')?.value||'';return allEntries().filter(e=>e.type===type&&(!search||`${e.description} ${e.category}`.toLowerCase().includes(search))&&(!cc||(e.costCenter||'Loja')===cc)&&(!status||(status==='overdue'?e.status!=='paid'&&e.dueDate<today():e.status===status))).sort((a,b)=>(a.dueDate||'').localeCompare(b.dueDate||''))}
window.renderFin3Accounts=function(){if($('fin3PayTable'))$('fin3PayTable').innerHTML=accountRows('payable').map(e=>accountTr(e,true)).join('')||'<tr><td colspan="7">Nenhuma conta encontrada.</td></tr>';if($('fin3RecTable'))$('fin3RecTable').innerHTML=accountRows('receivable').map(e=>accountTr(e,false)).join('')||'<tr><td colspan="6">Nenhum recebível encontrado.</td></tr>'}
function accountTr(e,pay){const overdue=e.status!=='paid'&&e.dueDate<today(),action=typeof window.toggleFinancePaid==='function'?`<button onclick="toggleFinancePaid('${e.id}');setTimeout(renderFinanceV10,80)">${e.status==='paid'?'Reabrir':'Baixar'}</button>`:'';return `<tr><td><b>${e.description||''}</b><br><small>${e.method||''}</small></td>${pay?`<td>${e.costCenter||'Loja'}</td><td>${e.category||'Outros'}</td>`:`<td>${e.category||e.method||'Venda'}</td>`}<td>${e.dueDate?new Date(e.dueDate+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td><b>${money(e.amount)}</b></td><td><span class="status ${e.status==='paid'?'good':overdue?'bad':''}">${e.status==='paid'?(pay?'Pago':'Recebido'):overdue?'Vencido':'Em aberto'}</span></td><td><div class="miniActions">${action}</div></td></tr>`}
function fillCostCenters(){const e=extra(),opts=e.centers.map(x=>`<option>${x}</option>`).join('');if($('finCostCenter'))$('finCostCenter').innerHTML=opts;if($('payCostCenter'))$('payCostCenter').innerHTML='<option value="">Todos centros</option>'+opts}
window.addCostCenter=function(){const n=prompt('Nome do novo centro de custo:');if(!n)return;const e=extra();if(!e.centers.includes(n))e.centers.push(n);saveExtra(e);renderBudget();fillCostCenters()}
window.saveBudgetPlan=function(){const e=extra();document.querySelectorAll('[data-budget-cat]').forEach(inp=>e.budget[inp.dataset.budgetCat]=num(inp.value));saveExtra(e);renderBudget();alert('Orçamento salvo.')}
function actualByCategory(cat){return allEntries().filter(x=>x.type==='payable'&&(x.category||'Outros')===cat&&((x.dueDate||x.paidAt||'').slice(0,7)===today().slice(0,7))).reduce((a,x)=>a+num(x.amount),0)}
function renderBudget(){if(!$('budgetTable'))return;const e=extra(),cats=[...new Set(defaultBudgetCats.concat(allEntries().map(x=>x.category||'Outros')))];$('budgetTable').innerHTML=cats.map(cat=>{const plan=num(e.budget[cat]),actual=actualByCategory(cat),delta=actual-plan,pct=plan?delta/plan*100:0;return `<tr><td><b>${cat}</b></td><td><input class="input budgetInput" data-budget-cat="${cat}" type="number" min="0" value="${plan||''}" placeholder="0"></td><td>${money(actual)}</td><td class="budgetDelta ${delta<=0?'good':'bad'}">${delta>=0?'+':''}${money(delta)} ${plan?`(${pct.toFixed(1)}%)`:''}</td><td><span class="status ${delta<=0?'good':pct>15?'bad':'warn'}">${delta<=0?'Dentro':pct>15?'Estourado':'Atenção'}</span></td></tr>`}).join('');$('costCenterList').innerHTML=e.centers.map((c,i)=>`<div class="costCenterChip"><span>${c}</span>${defaultCenters.includes(c)?'<small>Padrão</small>':`<button class="btn bad" onclick="removeCostCenter(${i})">Excluir</button>`}</div>`).join('');fillCostCenters()}
window.removeCostCenter=function(i){const e=extra();e.centers.splice(i,1);saveExtra(e);renderBudget()}
window.renderFinancialGoal=function(){if(!$('financialGoalResult'))return;const c=calcCore(),profitGoal=num($('goalProfit')?.value),marginGoal=num($('goalMargin')?.value)/100,contribution=c.rev?Math.max(.05,(c.rev-c.cmv)/c.rev):.45,fixed=c.paidExp||Math.max(10000,c.rev*.15),reqByProfit=(fixed+profitGoal)/contribution,reqByMargin=marginGoal<contribution?fixed/(contribution-marginGoal):reqByProfit,required=Math.max(reqByProfit,reqByMargin),falt=Math.max(0,required-c.rev),day=new Date().getDate(),daysMonth=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),remaining=Math.max(1,daysMonth-day);$('financialGoalResult').innerHTML=`<small>Faturamento necessário</small><strong>${money(required)}</strong><p>Já faturado: <b>${money(c.rev)}</b> · Falta: <b>${money(falt)}</b></p><div class="callout">Para chegar ao objetivo nos ${remaining} dias restantes, a loja precisa gerar aproximadamente <b>${money(falt/remaining)} por dia</b>.</div>`}
function renderScenario(){if(!$('scenarioResult'))return;const c=calcCore(),rv=num($('scRevenue')?.value||100),cv=num($('scCmv')?.value||100),ev=num($('scExpenses')?.value||100),disc=num($('scDiscount')?.value||0);[['scRevenueV',rv+'%'],['scCmvV',cv+'%'],['scExpensesV',ev+'%'],['scDiscountV',disc+'%']].forEach(x=>{if($(x[0]))$(x[0]).textContent=x[1]});const rev=c.rev*rv/100*(1-disc/100),cmv=c.cmv*cv/100,exp=c.paidExp*ev/100,profit=rev-cmv-exp,impact=profit-c.profit;$('scenarioResult').innerHTML=`<small>Lucro projetado no cenário</small><strong>${money(profit)}</strong><p>Impacto versus cenário atual: <b class="${impact>=0?'financeRiskLow':'financeRiskHigh'}">${impact>=0?'+':''}${money(impact)}</b></p><span class="status ${profit>=0?'good':'bad'}">Margem ${rev?(profit/rev*100).toFixed(1):'0.0'}%</span>`}
function productCost(id,item){const p=products().find(x=>x.id===id);return num(item?.cost||item?.custo||p?.cost||p?.custo||0)}
window.renderProfitability=function(){if(!$('profitTable'))return;const view=$('profitView')?.value||'category',groups={};sales().forEach(s=>(s.items||[]).forEach(i=>{const p=products().find(x=>x.id===i.id||x.id===i.productId)||{},key=view==='seller'?(s.sellerName||s.seller||'Sem vendedor'):view==='product'?(p.nome||p.name||i.name||'Produto'):(p.categoria||p.category||'Sem categoria'),qty=num(i.qty||1),rev=num(i.price||i.preco||0)*qty,cost=productCost(p.id||i.id,i)*qty;groups[key]=groups[key]||{rev:0,cost:0};groups[key].rev+=rev;groups[key].cost+=cost}));const rows=Object.entries(groups).map(([name,v])=>({name,...v,profit:v.rev-v.cost,margin:v.rev?(v.rev-v.cost)/v.rev*100:0})).sort((a,b)=>b.profit-a.profit),total=rows.reduce((a,r)=>a+r.rev,0);$('profitLabelHead').textContent=view==='seller'?'Vendedor':view==='product'?'Produto':'Categoria';$('profitTable').innerHTML=rows.slice(0,100).map(r=>`<tr><td><b>${r.name}</b></td><td>${money(r.rev)}</td><td>${money(r.cost)}</td><td><b>${money(r.profit)}</b></td><td><span class="status ${r.margin>=35?'good':r.margin<15?'bad':'warn'}">${r.margin.toFixed(1)}%</span></td><td><div class="profitBar"><i style="width:${total?r.rev/total*100:0}%"></i></div></td></tr>`).join('')||'<tr><td colspan="6">Sem vendas suficientes para calcular rentabilidade.</td></tr>';const best=rows[0],low=[...rows].filter(r=>r.rev>0).sort((a,b)=>a.margin-b.margin)[0];if($('profitKpis'))$('profitKpis').innerHTML=[['Lucro bruto',money(rows.reduce((a,r)=>a+r.profit,0))],['Margem média',total?(rows.reduce((a,r)=>a+r.profit,0)/total*100).toFixed(1)+'%':'0%'],['Maior resultado',best?.name||'—'],['Menor margem',low?`${low.name} · ${low.margin.toFixed(1)}%`:'—']].map(x=>`<div class="kpi"><div><small>${x[0]}</small><b>${x[1]}</b></div></div>`).join('')}
window.exportFinanceCsv=function(){const rows=[['Descrição','Tipo','Categoria','Centro de custo','Vencimento','Valor','Status']].concat(allEntries().map(e=>[e.description,e.type,e.category,e.costCenter||'Loja',e.dueDate,e.amount,e.status]));const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='ondis-financeiro-'+today()+'.csv';a.click();URL.revokeObjectURL(a.href)}
function renderFinanceV10(tab){renderExecutive();renderFin3Accounts();renderBudget();renderFinancialGoal();renderScenario();renderProfitability();if(typeof window.renderCardReconciliation==='function')try{window.renderCardReconciliation()}catch{} }
window.renderFinanceV10=renderFinanceV10;
// POS helpers
window.quickCheckout=function(method){if(typeof window.openCheckout==='function'){window.openCheckout();setTimeout(()=>{if($('checkoutPayment')){$('checkoutPayment').value=method;$('checkoutPayment').dispatchEvent(new Event('change'))}},30)}};
window.addCartNote=function(){const n=prompt('Observação da venda:');if(n){const e=extra();e.lastCartNote=n;saveExtra(e);alert('Observação adicionada à venda.')}};
window.filterPosCategory=function(cat){const input=$('saleSearch');if(!input)return;input.value=cat||'';input.dispatchEvent(new Event('input',{bubbles:true}))};
function renderPosStats(){if(!$('posTicket'))return;const ss=sales(),m=today().slice(0,7),ms=ss.filter(s=>(s.createdAt||'').slice(0,7)===m),ts=ss.filter(s=>(s.createdAt||'').slice(0,10)===today()),mr=ms.reduce((a,s)=>a+num(s.total),0);$('posTicket').textContent=money(ms.length?mr/ms.length:0);$('posSalesToday').textContent=ts.length;$('posSalesValue').textContent=money(ts.reduce((a,s)=>a+num(s.total),0));const last=[...ss].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))[0];$('posLastSale').textContent=last?money(last.total):'—';$('posLastSaleTime').textContent=last?.createdAt?new Date(last.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—';const cats=[...new Set(products().map(p=>p.categoria||p.category).filter(Boolean))];if($('posCategorySelect')&&$('posCategorySelect').options.length<=1)$('posCategorySelect').insertAdjacentHTML('beforeend',cats.map(c=>`<option>${c}</option>`).join(''))}
// dashboard resilience: if panels remain empty after app load, provide explicit empty states instead of blank boxes.
function ensureDashboardVisible(){['dashSellerRevenue','dashSellerConversion','dashFunnel','dashOutcomeDonut','dashLossReasons','dashAttendanceChart','dashRevenueChart'].forEach(id=>{const el=$(id);if(el&&!el.innerHTML.trim())el.innerHTML='<div class="dashboardEmptyList">Aguardando dados do período. O gráfico aparecerá automaticamente assim que houver movimentação.</div>'})}
function init(){bindFinNav();fillCostCenters();setTimeout(()=>{renderFinanceV10('executivo');renderPosStats();ensureDashboardVisible()},800);setInterval(renderPosStats,15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
